/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-18 05:27:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class editCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../Styles/styles.css\">\n");
      out.write("    <title>Tarpaulin - Edit a Course</title>\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"../Images/Tarpaulin_Logo_Alt_2.png\">\n");
      out.write("</head>\n");
      out.write("  <body class=\"studentHomeBody\">\n");
      out.write("    <script src=\"../Scripts/userTypeLocalStorage.js\"></script>\n");
      out.write("    <script src=\"../Scripts/userTypeLocalStorageAuthPageCheck.js\"></script>\n");
      out.write("    <script src=\"../Scripts/header.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"../Scripts/loadSidebar.js\"></script>\n");
      out.write("\n");
      out.write("    <section class=\"mainContainer profile\">\n");
      out.write("        <div class=\"top\">\n");
      out.write("            <div>\n");
      out.write("                <p>Edit a Course</p>\n");
      out.write("                <p>Modify information and add or remove tests and lectures</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <section class=\"profileSettings\">\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <p>Course Name</p>\n");
      out.write("                <input type=\"text\" placeholder=\"Name\" value=\"CSCI 123\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div style=\"flex-direction: column;\">\n");
      out.write("                <p>Course Description</p>\n");
      out.write("                <input type=\"text\" placeholder=\"Description\" value=\"Learn cool computer stuff.\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <section style=\"\n");
      out.write("                display: flex;\n");
      out.write("                flex-direction: row;\n");
      out.write("                margin-top: 2em;\n");
      out.write("                width: 40em;\n");
      out.write("            \">\n");
      out.write("                <section class=\"lectures\" style=\"\n");
      out.write("                    display: flex;\n");
      out.write("                    flex-direction: column;\n");
      out.write("                    width: 50%;\n");
      out.write("                    align-content: center;\n");
      out.write("                    padding-right: 2em;\n");
      out.write("                    border-right: 1px solid #00000050;\n");
      out.write("                \">\n");
      out.write("                    \n");
      out.write("                    <p style=\"font-size: 1.5em; font-weight: 500; color: var(--accentColor);\">Lectures</p>\n");
      out.write("\n");
      out.write("                    <button id=\"openAddLectureControls\" class=\"buttonAccent\" \n");
      out.write("                        onclick='document.getElementById(\"addLectureControls\").style.display=\"flex\"\n");
      out.write("                        document.getElementById(\"openAddLectureControls\").style.display=\"none\"'\n");
      out.write("                        style=\"margin: 0; margin-bottom: 1em; margin-top: 0.5em; align-self: center; font-size: 0.8em;\">Add Lecture</button>\n");
      out.write("\n");
      out.write("                    <section id=\"addLectureControls\" style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                        margin-top: 1em;\n");
      out.write("                        margin-bottom: 2em;\n");
      out.write("                        background-color: white;\n");
      out.write("                        padding: 10px;\n");
      out.write("                        padding-top: 25px;\n");
      out.write("                        padding-bottom: 15px;\n");
      out.write("                        border: 1px solid #00000050;\n");
      out.write("                        border-radius: 10px;\n");
      out.write("                        display: none;\n");
      out.write("                    \">\n");
      out.write("                        <div>\n");
      out.write("                            <p>Name</p>\n");
      out.write("                            <input type=\"text\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div>\n");
      out.write("                            <p>URL</p>\n");
      out.write("                            <input type=\"text\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <button class=\"buttonAccent\" style=\"\n");
      out.write("                            margin: 0;\n");
      out.write("                            margin-top: 2em;\n");
      out.write("                            align-self: center;\n");
      out.write("                        \" onclick='document.getElementById(\"addLectureControls\").style.display=\"none\";\n");
      out.write("                        document.getElementById(\"openAddLectureControls\").style.display=\"block\"'\n");
      out.write("                        >Confirm</button>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Your First Program</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Watch</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Change</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Intro to Data Types</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Watch</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Change</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Data Types Part 2</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Watch</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Change</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("                <section class=\"tests\" style=\"\n");
      out.write("                    display: flex;\n");
      out.write("                    flex-direction: column;\n");
      out.write("                    width: 50%;\n");
      out.write("                    align-content: center;\n");
      out.write("                    padding-left: 2em;\n");
      out.write("                \">\n");
      out.write("                    \n");
      out.write("                    <p style=\"font-size: 1.5em; font-weight: 500; color: var(--accentColor);\">Tests</p>\n");
      out.write("\n");
      out.write("                    <button class=\"buttonAccent\" style=\"margin: 0; margin-bottom: 1em; margin-top: 0.5em; align-self: center; font-size: 0.8em; height: 3em;\">Create Test</button>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Test 1</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">View</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Edit</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Test 1</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">View</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Edit</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"\n");
      out.write("                        display: flex;\n");
      out.write("                        flex-direction: column;\n");
      out.write("                    \">\n");
      out.write("                        <p>Test 1</p>\n");
      out.write("                        \n");
      out.write("                        <div class=\"controls\" style=\"display: flex; flex-direction: row;\">\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">View</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Edit</button>\n");
      out.write("                            <button class=\"buttonNormal\" style=\"font-size: 0.7em; margin: 0;\">Delete</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </section>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <script src=\"../Scripts/navbarToggle.js\"></script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
