/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-11 08:30:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Website.Pages;


public final class learnMore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../Styles/style.css\">\n");
      out.write("    <title>Tarpaulin - Learn More</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <script src=\"../Scripts/userTypeLocalStorage.js\"></script>\n");
      out.write("    <script src=\"../Scripts/header.js\"></script>\n");
      out.write("\n");
      out.write("    <section class=\"mainContainer\">\n");
      out.write("        <section class=\"titleBodySection\">\n");
      out.write("            <p class=\"bigTitle\">What exactly is Tarpaulin?</p>\n");
      out.write("            <div class=\"bodyText\">\n");
      out.write("                <p>\n");
      out.write("                    An actual detailed description would go here, so for now show: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor\n");
      out.write("                    incididunt ut labore et dolore magna aliqua. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Facilisis gravida neque convallis a cras semper. Scelerisque felis imperdiet proin fermentum leo vel. Duis at tellus at urna. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Pharetra massa massa ultricies mi quis. Sociis natoque penatibus et magnis dis parturient montes. Sed adipiscing diam donec adipiscing tristique. Sit amet tellus cras adipiscing enim. Sed blandit libero volutpat sed cras ornare arcu. Congue quisque egestas diam in arcu. Duis at tellus at urna condimentum mattis pellentesque id nibh. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Non curabitur gravida arcu ac tortor. Massa sapien faucibus et molestie. In cursus turpis massa tincidunt dui. Ut pharetra sit amet aliquam id diam.\n");
      out.write("                </p>\n");
      out.write("                <p>\n");
      out.write("                    Egestas dui id ornare arcu odio ut sem nulla pharetra. Magna eget est lorem ipsum dolor sit amet. Pellentesque adipiscing commodo elit at imperdiet dui. Tincidunt ornare massa eget egestas purus viverra accumsan. Sit amet massa vitae tortor condimentum. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Proin fermentum leo vel orci porta non pulvinar. Odio tempor orci dapibus ultrices in iaculis nunc. Nulla facilisi morbi tempus iaculis. Scelerisque eleifend donec pretium vulputate sapien.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"titleBodySection\">\n");
      out.write("            <p class=\"bigTitle\">FAQ</p>\n");
      out.write("\n");
      out.write("            <div class=\"faq\">\n");
      out.write("                <div>\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\">\n");
      out.write("                        <p class=\"questionText\">A question would go here?</p>\n");
      out.write("                        <p class=\"questionTextArrow\">^</p>\n");
      out.write("                    </label>\n");
      out.write("                    <p class=\"answer\">And an answer would go here, so for now: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Facilisis gravida neque convallis a cras semper. Scelerisque felis imperdiet proin fermentum leo vel.</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\">\n");
      out.write("                        <p class=\"questionText\">A question would go here?</p>\n");
      out.write("                        <p class=\"questionTextArrow\">^</p>\n");
      out.write("                    </label>\n");
      out.write("                    <p class=\"answer\">And an answer would go here, so for now: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Facilisis gravida neque convallis a cras semper. Scelerisque felis imperdiet proin fermentum leo vel.</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\">\n");
      out.write("                        <p class=\"questionText\">A question would go here?</p>\n");
      out.write("                        <p class=\"questionTextArrow\">^</p>\n");
      out.write("                    </label>\n");
      out.write("                    <p class=\"answer\">And an answer would go here, so for now: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Facilisis gravida neque convallis a cras semper. Scelerisque felis imperdiet proin fermentum leo vel.</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div>\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\">\n");
      out.write("                        <p class=\"questionText\">A question would go here?</p>\n");
      out.write("                        <p class=\"questionTextArrow\">^</p>\n");
      out.write("                    </label>\n");
      out.write("                    <p class=\"answer\">And an answer would go here, so for now: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Facilisis gravida neque convallis a cras semper. Scelerisque felis imperdiet proin fermentum leo vel.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <script src=\"../Scripts/faqAccordian.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
